name: Docker Build & Push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # IMAGE_NAME will use your Docker Hub username from secrets to build repo path
    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/messaging-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./messaging_app
          file: ./messaging_app/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Image info
        run: |
          echo "Pushed images:"
          echo "${{ env.IMAGE_NAME }}:latest"
          echo "${{ env.IMAGE_NAME }}:${{ github.sha }}"
